from typing import List, Dict, Any

SEED_PRODUCTS: List[Dict[str, Any]] = [
    # ------------------ LOANS (12 products) ------------------
    {
        "id": "loan-headline-bait",
        "name": "Prime Advantage Personal Loan",
        "provider": "MegaBank Corp",
        "category": "loan",
        "headline_rate": 8.5,
        "headline_label": "8.50% p.a.",
        "min_amount": 50000,
        "max_amount": 1500000,
        "min_tenure_months": 36,
        "max_tenure_months": 84,
        "lock_in_months": 12,
        "processing_fee_flat": 8000.0,
        "processing_fee_pct": 1.5,
        "prepayment_penalty_pct": 4.5,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "moderate",
        "liquidity_rating": "low",
        "tax_status": "taxable",
        "key_features": [
            "Attractive 8.5% headline interest rate",
            "Long tenure options up to 7 years",
            "Quick digital sanction"
        ],
        "secondary_conditions": [
            "Heavy ₹8,000 upfront processing fee",
            "4.5% foreclosure / prepayment penalty on outstanding principal",
            "Mandatory 7-year commitment defaults higher total interest if not exited"
        ],
        "badge": "Headline Rate Trap"
    },
    {
        "id": "loan-flexi-fit",
        "name": "Flexi-Term Smart Loan",
        "provider": "FinEdge Capital",
        "category": "loan",
        "headline_rate": 9.2,
        "headline_label": "9.20% p.a.",
        "min_amount": 30000,
        "max_amount": 1000000,
        "min_tenure_months": 12,
        "max_tenure_months": 36,
        "lock_in_months": 0,
        "processing_fee_flat": 2000.0,
        "processing_fee_pct": 0.5,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "high",
        "key_features": [
            "Zero prepayment penalty anytime",
            "Nominal ₹2,000 processing fee",
            "Custom 1 to 3 year repayment horizons"
        ],
        "secondary_conditions": [
            "Slightly higher advertised interest rate (9.2% vs 8.5%)",
            "Maximum tenure capped at 3 years"
        ],
        "badge": "High Suitability Fit"
    },
    {
        "id": "loan-instant-credit",
        "name": "SpeedyCash Quick Loan",
        "provider": "Zippy Fintech",
        "category": "loan",
        "headline_rate": 14.5,
        "headline_label": "14.50% p.a.",
        "min_amount": 10000,
        "max_amount": 300000,
        "min_tenure_months": 6,
        "max_tenure_months": 24,
        "lock_in_months": 0,
        "processing_fee_flat": 1500.0,
        "processing_fee_pct": 2.5,
        "prepayment_penalty_pct": 2.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "high",
        "liquidity_rating": "medium",
        "key_features": ["10-minute disbursement", "Minimal documentation", "Short tenures"],
        "secondary_conditions": ["Very high APR drag", "2.5% processing fee"],
        "badge": "High Cost"
    },
    {
        "id": "loan-green-vehicle",
        "name": "EcoDrive Green Auto Loan",
        "provider": "National Green Bank",
        "category": "loan",
        "headline_rate": 8.8,
        "headline_label": "8.80% p.a.",
        "min_amount": 100000,
        "max_amount": 2500000,
        "min_tenure_months": 24,
        "max_tenure_months": 60,
        "lock_in_months": 6,
        "processing_fee_flat": 3500.0,
        "processing_fee_pct": 0.75,
        "prepayment_penalty_pct": 1.5,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "medium",
        "key_features": ["Subsidized EV rate", "Flexible 2-5 year tenure", "Low processing fee"],
        "secondary_conditions": ["Vehicle hypothecation required", "1.5% prepayment fee within 24 months"],
        "badge": "Eco Specialist"
    },
    {
        "id": "loan-education-stepup",
        "name": "CareerBridge Education Loan",
        "provider": "Scholar Trust Bank",
        "category": "loan",
        "headline_rate": 9.5,
        "headline_label": "9.50% p.a.",
        "min_amount": 100000,
        "max_amount": 4000000,
        "min_tenure_months": 36,
        "max_tenure_months": 120,
        "lock_in_months": 12,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.5,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "high",
        "tax_status": "exempt_80e",
        "key_features": ["Section 80E tax deduction", "Moratorium period included", "Zero foreclosure charges"],
        "secondary_conditions": ["Course accreditation eligibility requirement"],
        "badge": "Tax Saver"
    },
    {
        "id": "loan-debt-consolidation",
        "name": "OnePay Debt Consolidation Facility",
        "provider": "Horizon Financial",
        "category": "loan",
        "headline_rate": 10.2,
        "headline_label": "10.20% p.a.",
        "min_amount": 100000,
        "max_amount": 2000000,
        "min_tenure_months": 24,
        "max_tenure_months": 60,
        "lock_in_months": 0,
        "processing_fee_flat": 4000.0,
        "processing_fee_pct": 1.0,
        "prepayment_penalty_pct": 1.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "moderate",
        "liquidity_rating": "medium",
        "key_features": ["Direct settlement with multiple creditors", "Single unified monthly EMI"],
        "secondary_conditions": ["Requires closing existing credit lines"],
        "badge": "Debt Relief"
    },
    {
        "id": "loan-overdraft-plus",
        "name": "FlexiLine Salary Overdraft",
        "provider": "Apex Commercial Bank",
        "category": "loan",
        "headline_rate": 11.5,
        "headline_label": "11.50% p.a.",
        "min_amount": 25000,
        "max_amount": 500000,
        "min_tenure_months": 12,
        "max_tenure_months": 36,
        "lock_in_months": 0,
        "processing_fee_flat": 1000.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "high",
        "key_features": ["Pay interest only on utilized amount", "No prepayment charges", "Reusable credit line"],
        "secondary_conditions": ["Annual renewal fee ₹1,000", "Higher base rate than term loans"],
        "badge": "High Liquidity"
    },
    {
        "id": "loan-gold-secure",
        "name": "Suraksha Secured Gold Loan",
        "provider": "Muthoot Apex",
        "category": "loan",
        "headline_rate": 8.2,
        "headline_label": "8.20% p.a.",
        "min_amount": 25000,
        "max_amount": 3000000,
        "min_tenure_months": 6,
        "max_tenure_months": 24,
        "lock_in_months": 0,
        "processing_fee_flat": 500.0,
        "processing_fee_pct": 0.25,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "high",
        "key_features": ["Lowest interest rate", "Bullet repayment option", "Minimal fee"],
        "secondary_conditions": ["Physical collateral required", "Auction risk on default"],
        "badge": "Collateralized"
    },
    {
        "id": "loan-p2p-express",
        "name": "PeerMatch Community Loan",
        "provider": "LendFair P2P",
        "category": "loan",
        "headline_rate": 12.0,
        "headline_label": "12.00% p.a.",
        "min_amount": 20000,
        "max_amount": 400000,
        "min_tenure_months": 12,
        "max_tenure_months": 36,
        "lock_in_months": 3,
        "processing_fee_flat": 2500.0,
        "processing_fee_pct": 2.0,
        "prepayment_penalty_pct": 3.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "moderate",
        "liquidity_rating": "medium",
        "key_features": ["Flexible credit score underwriting", "Direct investor matching"],
        "secondary_conditions": ["2% platform matchmaking fee", "3% foreclosure penalty"],
        "badge": "P2P Credit"
    },
    {
        "id": "loan-premium-salaried",
        "name": "Elite Executive Unsecured Loan",
        "provider": "Standard Chartered Apex",
        "category": "loan",
        "headline_rate": 9.9,
        "headline_label": "9.90% p.a.",
        "min_amount": 200000,
        "max_amount": 5000000,
        "min_tenure_months": 24,
        "max_tenure_months": 72,
        "lock_in_months": 12,
        "processing_fee_flat": 5000.0,
        "processing_fee_pct": 1.0,
        "prepayment_penalty_pct": 2.5,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "moderate",
        "liquidity_rating": "low",
        "key_features": ["High loan quantum", "Complimentary insurance cover"],
        "secondary_conditions": ["Minimum salary threshold ₹50,000/mo", "Lock-in 12 months"],
        "badge": "High Quantum"
    },
    {
        "id": "loan-micro-sme",
        "name": "Pragati Micro-Enterprise Credit",
        "provider": "Gramin Small Finance Bank",
        "category": "loan",
        "headline_rate": 13.5,
        "headline_label": "13.50% p.a.",
        "min_amount": 25000,
        "max_amount": 500000,
        "min_tenure_months": 12,
        "max_tenure_months": 48,
        "lock_in_months": 0,
        "processing_fee_flat": 1200.0,
        "processing_fee_pct": 1.5,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "moderate",
        "liquidity_rating": "medium",
        "key_features": ["Doorstep service", "No collateral up to ₹1L", "Zero foreclosure fee"],
        "secondary_conditions": ["Higher interest spread"],
        "badge": "Micro Credit"
    },
    {
        "id": "loan-festival-promo",
        "name": "Festive Zero-Charge Special Loan",
        "provider": "Urban Trust Bank",
        "category": "loan",
        "headline_rate": 10.5,
        "headline_label": "10.50% p.a.",
        "min_amount": 50000,
        "max_amount": 1000000,
        "min_tenure_months": 12,
        "max_tenure_months": 60,
        "lock_in_months": 6,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 1.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "high",
        "key_features": ["Zero processing fee promotion", "Transparent terms"],
        "secondary_conditions": ["Limited promotional tenure validity"],
        "badge": "Zero Fee Promo"
    },

    # ------------------ INVESTMENTS (10 products) ------------------
    {
        "id": "inv-hybrid-growth",
        "name": "Balanced Advantage Dynamic Fund",
        "provider": "HDFC Asset Management",
        "category": "investment",
        "headline_rate": 12.2,
        "headline_label": "12.20% CAGR",
        "min_amount": 5000,
        "max_amount": 50000000,
        "min_tenure_months": 36,
        "max_tenure_months": 120,
        "lock_in_months": 0,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 1.0, # if exited within 12 months
        "expense_ratio_pct": 0.75,
        "risk_level": "moderate",
        "liquidity_rating": "high",
        "tax_status": "equity_ltcg",
        "key_features": [
            "Dynamic asset allocation between equity and debt",
            "Lower volatility than pure equity",
            "Optimal for 3-5 year holding horizon"
        ],
        "secondary_conditions": [
            "1.0% exit load if redeemed before 365 days",
            "0.75% ongoing annual expense ratio drag",
            "Returns are market linked and not guaranteed"
        ],
        "badge": "Top Moderate Choice"
    },
    {
        "id": "inv-crypto-momentum",
        "name": "Alpha Dynamic Crypto Index Basket",
        "provider": "BitFlow Asset Labs",
        "category": "investment",
        "headline_rate": 28.5,
        "headline_label": "28.50% Hist. Return",
        "min_amount": 5000,
        "max_amount": 10000000,
        "min_tenure_months": 6,
        "max_tenure_months": 36,
        "lock_in_months": 0,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 1.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 2.5,
        "expense_ratio_pct": 2.0,
        "risk_level": "high",
        "liquidity_rating": "medium",
        "tax_status": "taxable_30pct_flat",
        "key_features": [
            "Very high historical upside potential",
            "Unrestricted liquidity anytime"
        ],
        "secondary_conditions": [
            "Extreme downside volatility (historical max drawdown > 65%)",
            "Flat 30% tax on gains with zero loss set-off",
            "High 2.0% management fee + 2.5% redemption slippage",
            "Strictly unsuitable for low financial capacity buffers"
        ],
        "badge": "High Volatility Warning"
    },
    {
        "id": "inv-elss-taxsaver",
        "name": "Mirae Tax Shield ELSS Fund",
        "provider": "Mirae Asset Mutual Fund",
        "category": "investment",
        "headline_rate": 14.8,
        "headline_label": "14.80% 3Yr CAGR",
        "min_amount": 1000,
        "max_amount": 150000,
        "min_tenure_months": 36,
        "max_tenure_months": 120,
        "lock_in_months": 36, # strict 3-year statutory lock-in
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.65,
        "risk_level": "high",
        "liquidity_rating": "low",
        "tax_status": "exempt_80c",
        "key_features": [
            "Section 80C tax deduction up to ₹1.5 Lakh",
            "Pure large & midcap wealth creation",
            "Zero exit load after lock-in"
        ],
        "secondary_conditions": [
            "Zero premature liquidity: 36-month non-negotiable statutory lock-in",
            "Equity market volatility exposure"
        ],
        "badge": "80C Tax Saver"
    },
    {
        "id": "inv-corporate-bond",
        "name": "Bharat AAA Corporate Bond Fund",
        "provider": "ICICI Prudential Asset Management",
        "category": "investment",
        "headline_rate": 8.4,
        "headline_label": "8.40% Yield to Maturity",
        "min_amount": 10000,
        "max_amount": 10000000,
        "min_tenure_months": 24,
        "max_tenure_months": 60,
        "lock_in_months": 0,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.25,
        "expense_ratio_pct": 0.35,
        "risk_level": "low",
        "liquidity_rating": "high",
        "tax_status": "debt_slab_tax",
        "key_features": [
            "100% AAA-rated sovereign & high-grade enterprise debt",
            "Stable predictable yields",
            "Low volatility"
        ],
        "secondary_conditions": [
            "Gains taxed at marginal income slab rate",
            "Interest rate cycle duration risk"
        ],
        "badge": "Stable Anchor"
    },
    {
        "id": "inv-nifty50-index",
        "name": "Nifty 50 Ultra Low-Cost Index Fund",
        "provider": "UTI Mutual Fund",
        "category": "investment",
        "headline_rate": 13.1,
        "headline_label": "13.10% 5Yr CAGR",
        "min_amount": 500,
        "max_amount": 50000000,
        "min_tenure_months": 60,
        "max_tenure_months": 240,
        "lock_in_months": 0,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.15,
        "risk_level": "moderate",
        "liquidity_rating": "high",
        "tax_status": "equity_ltcg",
        "key_features": [
            "Industry-lowest expense ratio (0.15%)",
            "Zero exit load anytime",
            "Direct replication of India's top 50 blue chips"
        ],
        "secondary_conditions": [
            "Requires at least 5-year investment horizon for equity risk mitigation"
        ],
        "badge": "Passive Bluechip"
    },
    {
        "id": "inv-reit-income",
        "name": "Nexus Commercial Real Estate Yield Trust (REIT)",
        "provider": "Nexus Select Trust",
        "category": "investment",
        "headline_rate": 7.9,
        "headline_label": "7.90% Dist. Yield",
        "min_amount": 15000,
        "max_amount": 5000000,
        "min_tenure_months": 36,
        "max_tenure_months": 84,
        "lock_in_months": 0,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.50,
        "risk_level": "moderate",
        "liquidity_rating": "medium",
        "tax_status": "partially_tax_free_dividend",
        "key_features": ["Quarterly cash dividend distribution", "Grade-A office rental backing"],
        "secondary_conditions": ["Stock exchange trade liquidity dependency"],
        "badge": "Regular Income"
    },
    {
        "id": "inv-sovereign-gold",
        "name": "Reserve Bank Sovereign Gold Bond (SGB)",
        "provider": "Government of India / RBI",
        "category": "investment",
        "headline_rate": 10.5,
        "headline_label": "2.5% + Gold Apprec.",
        "min_amount": 6000,
        "max_amount": 2500000,
        "min_tenure_months": 60,
        "max_tenure_months": 96,
        "lock_in_months": 60,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "low",
        "tax_status": "tax_free_on_maturity",
        "key_features": ["Zero capital gains tax on 8-year maturity", "Additional 2.50% annual interest payout"],
        "secondary_conditions": ["5-year early redemption lockout with RBI"],
        "badge": "Sovereign Gold"
    },
    {
        "id": "inv-smallcap-alpha",
        "name": "Nippon India Small Cap Power Fund",
        "provider": "Nippon Life India AMC",
        "category": "investment",
        "headline_rate": 21.4,
        "headline_label": "21.40% 5Yr CAGR",
        "min_amount": 5000,
        "max_amount": 10000000,
        "min_tenure_months": 84,
        "max_tenure_months": 180,
        "lock_in_months": 0,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 1.0,
        "expense_ratio_pct": 0.90,
        "risk_level": "high",
        "liquidity_rating": "medium",
        "tax_status": "equity_ltcg",
        "key_features": ["High compounding alpha in emerging leaders"],
        "secondary_conditions": ["High standard deviation & cyclical drawdowns", "Requires 7+ years commitment"],
        "badge": "Aggressive Growth"
    },
    {
        "id": "inv-arbitrage-liquid",
        "name": "Kotak Equity Arbitrage Liquidity Fund",
        "provider": "Kotak Mahindra Mutual Fund",
        "category": "investment",
        "headline_rate": 7.3,
        "headline_label": "7.30% Ann. Return",
        "min_amount": 5000,
        "max_amount": 50000000,
        "min_tenure_months": 3,
        "max_tenure_months": 24,
        "lock_in_months": 0,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.25,
        "expense_ratio_pct": 0.30,
        "risk_level": "low",
        "liquidity_rating": "high",
        "tax_status": "equity_taxation_advantage",
        "key_features": ["Equity taxation for low-risk liquid returns", "30-day exit load only"],
        "secondary_conditions": ["Yields fluctuate with cash-futures spread"],
        "badge": "Tax-Smart Cash"
    },
    {
        "id": "inv-target-maturity",
        "name": "Edelweiss Bharat Bond Target Maturity 2030",
        "provider": "Edelweiss Asset Management",
        "category": "investment",
        "headline_rate": 7.7,
        "headline_label": "7.70% YTM (2030)",
        "min_amount": 1000,
        "max_amount": 10000000,
        "min_tenure_months": 48,
        "max_tenure_months": 60,
        "lock_in_months": 0,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.10,
        "expense_ratio_pct": 0.05,
        "risk_level": "low",
        "liquidity_rating": "high",
        "tax_status": "debt_slab_tax",
        "key_features": ["Defined maturity lock-in yield", "PSU CPSE bond safety", "Ultra-low 0.05% fee"],
        "secondary_conditions": ["Price fluctuation if sold before 2030 maturity date"],
        "badge": "Target Maturity"
    },

    # ------------------ SAVINGS & FIXED DEPOSITS (8 products) ------------------
    {
        "id": "sav-flexi-fd",
        "name": "Smart-Saver Auto-Sweep Flexi FD",
        "provider": "HDFC Commercial Bank",
        "category": "savings",
        "headline_rate": 6.8,
        "headline_label": "6.80% p.a.",
        "min_amount": 10000,
        "max_amount": 10000000,
        "min_tenure_months": 6,
        "max_tenure_months": 36,
        "lock_in_months": 0,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "high",
        "tax_status": "tds_applicable",
        "key_features": [
            "Auto-sweep breaks only the exact amount required",
            "Zero premature withdrawal penalty",
            "DICGC ₹5 Lakh deposit insurance backing"
        ],
        "secondary_conditions": [
            "Interest fully taxable as per income tax slab"
        ],
        "badge": "Emergency Buffer Hero"
    },
    {
        "id": "sav-highyield-locked-fd",
        "name": "MaxiYield 5-Year Term Deposit",
        "provider": "Suryoday Small Finance Bank",
        "category": "savings",
        "headline_rate": 8.6,
        "headline_label": "8.60% p.a.",
        "min_amount": 25000,
        "max_amount": 5000000,
        "min_tenure_months": 60,
        "max_tenure_months": 60,
        "lock_in_months": 12,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 1.5,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "low",
        "tax_status": "tds_applicable",
        "key_features": [
            "Industry-leading 8.60% guaranteed interest",
            "DICGC insured up to ₹5 Lakh"
        ],
        "secondary_conditions": [
            "1.5% interest rate penalty on premature withdrawal",
            "Mandatory 12-month lock before withdrawal permitted",
            "Unsuitable if emergency fund is inadequate"
        ],
        "badge": "High Yield Lock"
    },
    {
        "id": "sav-digital-high-yield",
        "name": "NeoBoost High-Yield Digital Savings",
        "provider": "AUM Neo Digital Bank",
        "category": "savings",
        "headline_rate": 7.0,
        "headline_label": "7.00% Daily Int.",
        "min_amount": 1000,
        "max_amount": 2500000,
        "min_tenure_months": 1,
        "max_tenure_months": 120,
        "lock_in_months": 0,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "high",
        "tax_status": "section_80tta_applicable",
        "key_features": ["Daily interest calculation", "Unlimited free UPI & ATM withdrawals", "Section 80TTA deduction up to ₹10,000"],
        "secondary_conditions": ["Tiered rate: 7.0% applies only on balance > ₹1,00,000; 3.5% on lower balance"],
        "badge": "Digital Liquid"
    },
    {
        "id": "sav-senior-citizen-special",
        "name": "Vridhi Senior Citizen Super FD",
        "provider": "Canara State Bank",
        "category": "savings",
        "headline_rate": 8.0,
        "headline_label": "8.00% p.a.",
        "min_amount": 10000,
        "max_amount": 1500000,
        "min_tenure_months": 36,
        "max_tenure_months": 60,
        "lock_in_months": 0,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.5,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "medium",
        "tax_status": "section_80ttb_applicable",
        "key_features": ["0.50% extra rate for age 60+", "Monthly pension payout option", "Section 80TTB ₹50k exemption"],
        "secondary_conditions": ["Strict age verification (60+ years required)"],
        "badge": "Senior Citizen"
    },
    {
        "id": "sav-recurring-deposit",
        "name": "Lakshya Monthly Recurring Deposit",
        "provider": "Axis Union Bank",
        "category": "savings",
        "headline_rate": 7.1,
        "headline_label": "7.10% p.a.",
        "min_amount": 2000,
        "max_amount": 100000,
        "min_tenure_months": 12,
        "max_tenure_months": 36,
        "lock_in_months": 6,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 1.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "medium",
        "tax_status": "tds_applicable",
        "key_features": ["Disciplined monthly automated savings habit", "Quarterly compounding interest"],
        "secondary_conditions": ["Penalty charged on missed monthly installment"],
        "badge": "Habit Builder"
    },
    {
        "id": "sav-tax-saving-fd",
        "name": "5-Year Statutory Tax-Saver FD",
        "provider": "State Bank of India",
        "category": "savings",
        "headline_rate": 6.5,
        "headline_label": "6.50% p.a.",
        "min_amount": 10000,
        "max_amount": 150000,
        "min_tenure_months": 60,
        "max_tenure_months": 60,
        "lock_in_months": 60,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "low",
        "tax_status": "exempt_80c",
        "key_features": ["Section 80C deduction up to ₹1.5L", "Guaranteed sovereign-grade security"],
        "secondary_conditions": ["Strict non-negotiable 5-year lock-in (no premature withdrawal or loan against FD)"],
        "badge": "80C Lock"
    },
    {
        "id": "sav-corporate-fd",
        "name": "Bajaj Finance High Yield Corporate Deposit",
        "provider": "Bajaj Finance NBFC",
        "category": "savings",
        "headline_rate": 8.25,
        "headline_label": "8.25% p.a.",
        "min_amount": 15000,
        "max_amount": 5000000,
        "min_tenure_months": 24,
        "max_tenure_months": 48,
        "lock_in_months": 3,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 2.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "medium",
        "tax_status": "tds_applicable",
        "key_features": ["CRISIL AAA rating", "Higher interest than standard commercial bank FDs"],
        "secondary_conditions": ["Not covered under RBI DICGC insurance scheme", "2% premature interest reduction"],
        "badge": "NBFC High Yield"
    },
    {
        "id": "sav-short-term-treasury",
        "name": "91-Day Sovereign T-Bill Direct",
        "provider": "Reserve Bank of India (Retail Direct)",
        "category": "savings",
        "headline_rate": 6.75,
        "headline_label": "6.75% Disc. Yield",
        "min_amount": 10000,
        "max_amount": 20000000,
        "min_tenure_months": 3,
        "max_tenure_months": 3,
        "lock_in_months": 3,
        "processing_fee_flat": 0.0,
        "processing_fee_pct": 0.0,
        "prepayment_penalty_pct": 0.0,
        "exit_load_pct": 0.0,
        "expense_ratio_pct": 0.0,
        "risk_level": "low",
        "liquidity_rating": "high",
        "tax_status": "slab_rate",
        "key_features": ["Zero credit risk backed by RBI", "Direct institutional rate access"],
        "secondary_conditions": ["Short 91-day maturity requiring manual reinvestment rollover"],
        "badge": "RBI Direct"
    }
]

DEMO_PERSONAS: List[Dict[str, Any]] = [
    {
        "id": "persona-loan-trap",
        "name": "Rohan (The 3-Year Vehicle Seeker)",
        "tagline": "Headline Rate Trap Scenario",
        "description": "24 years old, ₹35k income, seeks ₹2,00,000 for a vehicle, intends to repay/exit in 3 years. Will headline 8.5% beat 9.2%?",
        "category": "loan",
        "scenario_focus": "Exposes why Loan A (8.5%, ₹8k fee, 4.5% prepay penalty, 7yr tenure) loses to Loan B (9.2%, ₹2k fee, 0% prepay, 3yr tenure) in total cost and suitability.",
        "profile": {
            "name": "Rohan Sharma",
            "age": 24,
            "monthly_income": 35000.0,
            "monthly_expenses": 25000.0,
            "existing_debt_emi": 2000.0,
            "current_savings": 75000.0,
            "financial_goal": "vehicle_purchase",
            "category_interest": "loan",
            "target_amount": 200000.0,
            "target_horizon_months": 36,
            "risk_tolerance": "moderate",
            "liquidity_importance": "medium",
            "prepayment_preference": "very_likely"
        }
    },
    {
        "id": "persona-risk-mismatch",
        "name": "Aarav (The Risk Mismatch)",
        "tagline": "Tolerance vs Capacity Conflict Scenario",
        "description": "Earning ₹25k with ₹23k expenses and only ₹10k savings. Self-declares HIGH risk tolerance, but actual financial buffer is critically thin.",
        "category": "investment",
        "scenario_focus": "AlignFin overrides subjective hype, flags 'RISK MISMATCH', penalizes volatile crypto/smallcap assets, and directs user to capital preservation.",
        "profile": {
            "name": "Aarav Patel",
            "age": 22,
            "monthly_income": 25000.0,
            "monthly_expenses": 23000.0,
            "existing_debt_emi": 0.0,
            "current_savings": 10000.0,
            "financial_goal": "wealth_growth",
            "category_interest": "investment",
            "target_amount": 10000.0,
            "target_horizon_months": 12,
            "risk_tolerance": "high",
            "liquidity_importance": "high",
            "prepayment_preference": "unlikely"
        }
    },
    {
        "id": "persona-5yr-wealth",
        "name": "Priya (5-Year Balanced Builder)",
        "tagline": "Optimal Horizon & Hybrid Allocation",
        "description": "28 years old, ₹65k income, ₹30k expenses, ₹2.5 Lakh savings. Moderate risk, seeking disciplined 5-year wealth accumulation.",
        "category": "investment",
        "scenario_focus": "Shows how dynamic balanced hybrid & passive index funds achieve top suitability while avoiding rigid statutory lock-ins and excessive volatility.",
        "profile": {
            "name": "Priya Sundaram",
            "age": 28,
            "monthly_income": 65000.0,
            "monthly_expenses": 30000.0,
            "existing_debt_emi": 5000.0,
            "current_savings": 250000.0,
            "financial_goal": "wealth_growth",
            "category_interest": "investment",
            "target_amount": 100000.0,
            "target_horizon_months": 60,
            "risk_tolerance": "moderate",
            "liquidity_importance": "medium",
            "prepayment_preference": "unlikely"
        }
    },
    {
        "id": "persona-emergency-builder",
        "name": "Sneha (Emergency Cushion Planner)",
        "tagline": "Liquidity & Zero-Penalty Buffer",
        "description": "31 years old with young family, prioritizing 100% accessible liquidity with guaranteed returns for peace of mind.",
        "category": "savings",
        "scenario_focus": "Demonstrates why auto-sweep flexi deposits outrank locked 5-year fixed deposits even when the locked deposit advertises 8.6% vs 6.8%.",
        "profile": {
            "name": "Sneha Verma",
            "age": 31,
            "monthly_income": 50000.0,
            "monthly_expenses": 38000.0,
            "existing_debt_emi": 4000.0,
            "current_savings": 40000.0,
            "financial_goal": "emergency_fund",
            "category_interest": "savings",
            "target_amount": 100000.0,
            "target_horizon_months": 12,
            "risk_tolerance": "low",
            "liquidity_importance": "high",
            "prepayment_preference": "very_likely"
        }
    }
]
